project_name: tenderdash

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: "Tenderdash"
    main: ./cmd/tenderdash/main.go
    ldflags:
      - -s -w -X github.com/ktechmidas/tenderdash/version.TMCoreSemVer={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  name_template: "{{.Version}} (WARNING: BETA SOFTWARE)"
